import {Platform} from 'react-native';
const COLORS = {
  ELEVATION: 5,
  BORDER_COLOR: "#989AA0",
  SOICALCOLOR:"#F5F4F4",
  HEADERCOLOR:"#7D94EC",
  LIGHTBG:"#D4DFFF",
  MAINBACKGROUNDCOLOR:"#F0F0F8",
  BASELIGHTCOLOR:"#E5ECFF",
  TEXTCOLORBG:"#5C7AEC",
  GRAYTEXTCOLOR:"#989BA5",
  FALSHCARDTEXTCOLOR:"#4284F4",
  CHATCOLOR1:"#2B7BF4",
  CHATCOLOR2:"#4EC8FD",
  EVENTDATECOLOR:"#E5EBFF",
  SUCCESSCOLOR:"#4FC871",
  DULLBUTTONCOLOR:"#E3EAF9",
  GAMIFICATIONHEADER:"#EDF1FF",

  DUMMYPROFILEBACKGROUNDCOLOR:"#E4E6F7",
  TEXTCOLOR:"#2B2B2F",
  BOARDERBASECOLOR:"#D4DDFF",
  LIGHTBLUECOLOR:"#E1E7FB",
  //theme colors
  DEFAULT: '#EBF3FF',
  SECONDARY: '#5453EE',
  SKIPSECONDARY:"#CCCAF366",
  PRIMARY: '#7D94EC',
  PRIMARY_DARK: '#003F89',
  LINEAR_GRADIENT_COLORS: ['#20ABF3', '#3B4EBF', '#2D005B'],

  ONBOARDINGDOTES_COLOR:["#FFFFFF", "#4665DA"],

  //colors
  WHITE: '#FFFFFF',
  LIGHTRED:"#FFE5E5",
  BG_COLOR: '#FFFFFF',
  LIGHT_SILVER: '#F8F7F7',
  BLACK_OPACITY: '#00000050',
  BLACK: '#000000',
  SILVER: '#9D9D9D',
  DISABLED: '#CCCAF366',
  DISABLEDTEXT:"#BEC2D0",
  // DISABLED: '#cccccc',
  GRAY: '#808080',
  GREEN: '#36D776',
  LIGHTGREEN:"rgba(76, 175, 80, 0.09)",
  RED: '#ff0000',
  ORANGE: 'orange',
  TRANSPARENT: 'transparent',
  PLACEHOLDER_COLOR: '#8F9BB3',
  CREAM_COLOR: '#EFEFEF',
  LIGHT_GRAY: '#F4F4F4',
  LIGHT_BLUE: '#e9f0f5',

  //shadow
  SHADOW_COLOR_IOS: 'silver',
  SHADOW_COLOR_ANDROID: 'black',
  SHADOW_COLOR: Platform.OS == 'android' ? '#808080' : 'silver'
};

export default COLORS;
