const path = '../assets/images/';
const mockPath = '../assets/images/mocks/';
const jsonpath = '../assets/json/';

const IMAGES = {
  //demo file
  DEMO_PIC_RANDOM: 'https://picsum.photos/300/600?random=',
  DEMO_PIC: 'https://picsum.photos/300/600',

  // json file
  FreshUser: require(jsonpath + 'LMSFreshUserJson.json'),
  wave: require(jsonpath + 'wave.json'),
  ConfettiAnimation:require(jsonpath + 'ConfettiAnimation.json'),
  CourseCompleted:require(jsonpath + 'CourseCompleted.json'),
  CourseNotPassed:require(jsonpath + 'CourseNotPassed.json'),
  CoursePassed:require(jsonpath + 'CoursePassed.json'),

  // png file
  // new
  en: require(path + 'en.png'),
  bul: require(path + 'bul.png'),

  onBoarding1: require(path + 'onBoarding1.png'),
  onBoarding2: require(path + 'onBoarding2.png'),
  onBoarding3: require(path + 'onBoarding3.png'),
  
  facebookSoicalLogin: require(path + 'facebookSoicalLogin.png'),
  googleSoicalLogin: require(path + 'googleSoicalLogin.png'),
  microsoftSoicalLogin: require(path + 'microsoftSoicalLogin.png'),

  backArrowLeft: require(path + 'backArrowLeft.png'),

  calendardaysImage: require(path + 'calendardaysImage.png'),
  headerProfileDummyIcon: require(path + 'headerProfileDummyIcon.png'),
  upcomingEventLayoutImage: require(path + 'upcomingEventLayoutImage.png'),
  circleChevronRight: require(path + 'circleChevronRight.png'),
  dummyPathCard: require(path + 'dummyPathCard.png'),
  dummyFlashCard: require(path + 'dummyFlashCard.png'),
  circleXmark: require(path + 'circleXmark.png'),
  calendarCockCard: require(path + 'calendarCockCard.png'),
  attachmetPin: require(path + 'attachmetPin.png'),
  crownImage: require(path + 'crownImage.png'),
  boltImage: require(path + 'boltImage.png'),

  arrowRight: require(path + 'arrowRight.png'),
  arrowRightBracket: require(path + 'arrowRightBracket.png'),
  lockKeyhole: require(path + 'lockKeyhole.png'),
  penLine: require(path + 'penLine.png'),
  chartFilter: require(path + 'chartFilter.png'),
  EventClock: require(path + 'EventClock.png'),
  flashCardBackgroundImage: require(path + 'flashCardBackgroundImage.png'),
  businessImage: require(path + 'businessImage.png'),
  volumeIcon: require(path + 'volumeIcon.png'),
  lightBulb: require(path + 'lightBulb.png'),
  checked: require(path + 'checked.png'),
  unchecked: require(path + 'unchecked.png'),
  chevronDown: require(path + 'chevronDown.png'),
  circleClock: require(path + 'circleClock.png'),
  circleQuestion: require(path + 'circleQuestion.png'),
  fileLines: require(path + 'fileLines.png'),
  filePdf: require(path + 'filePdf.png'),
  calendarBlue: require(path + 'calendarBlue.png'),
  clockBlue: require(path + 'clockBlue.png'),
  linkIconBlue: require(path + 'linkIconBlue.png'),
  userGroupBlue: require(path + 'userGroupBlue.png'),
  locationDot: require(path + 'locationDot.png'),
  pathChartLine: require(path + 'pathChartLine.png'),
  courseChartLine: require(path + 'courseChartLine.png'),
  LineBlank: require(path + 'LineBlank.png'),
  LMSFreshUser: require(path + 'LMSFreshUser.svg'),
  GroupImage: require(path + 'GroupImage.png'),
  missingDocument: require(path + 'missingDocument.png'),
  houseGoToHome: require(path + 'houseGoToHome.png'),
  crossImage: require(path + 'crossImage.png'),
  checkImage: require(path + 'checkImage.png'),
  lockKeyhole1:require(path + 'lockKeyhole1.png'),
  EllipseSoftBoard:require(path + 'EllipseSoftBoard.png'),
  EllipseDarkBoard:require(path + 'EllipseDarkBoard.png'),
  crownLeaderBoard:require(path + 'crownLeaderBoard.png'),
  boltLeaderBoard:require(path + 'boltLeaderBoard.png'),
  trophyStarLeaderBoard:require(path + 'trophyStarLeaderBoard.png'),
  medalLeaderBoard:require(path + 'medalLeaderBoard.png'),
  BudgesReal:require(path + 'BudgesReal.jpg'),
  trophyStarBlur:require(path + 'trophyStarBlur.png'),
  medalBlur:require(path + 'medalBlur.png'),
  appleLogo:require(path + 'appleLogo.png'),
  gamificationPointImage: require(path + 'gamificationPointImage.png'),
  failFaceSmile:require(path + 'failFaceSmile.png'),
  successFaceSmile: require(path + 'successFaceSmile.png'),
  search: require(path + 'search.png'),
  fileLinesImage:require(path + 'fileLinesImage.png'),
  checkCircleImage:require(path + 'checkCircleImage.png'),
  expandImage:require(path + 'expandImage.png'),
  miniClock:require(path + 'miniClock.png'),
  angleDownIcon:require(path + 'angleDownIcon.png'),
  angleUpIcon:require(path + 'angleUpIcon.png'),
  PdfSmallIcon:require(path + 'PdfSmallIcon.png'),
  DownloadIcon:require(path + 'DownloadIcon.png'),
  uploadFileViewImage:require(path + 'uploadFileViewImage.png'),
  xmarkIcon:require(path + 'xmarkIcon.png'),
  VectorIcon:require(path + 'VectorIcon.png'),
  circleCheck:require(path + 'circleCheck.png'),
  informationIcon:require(path + 'informationIcon.png'),
  FrameBulb:require(path + 'FrameBulb.png'),
  trophyStar: require(path + 'trophyStar.png'),
  commentImage: require(path + 'commentImage.png'),
  circleInfo: require(path + 'circleInfo.png'),

  arrowRotateRight: require(path + 'arrowRotateRight.png'),
  clipboardListCheckBlue: require(path + 'clipboardListCheckBlue.png'),
  circlePlay: require(path + 'circlePlay.png'),
  clipboardListCheckGray: require(path + 'clipboardListCheckGray.png'),
  clockGray: require(path + 'clockGray.png'),
  dCheckList: require(path + 'dCheckList.png'),
  businessmanShowing: require(path + 'businessmanShowing.png'),
  gripDotsVertical: require(path + 'gripDotsVertical.png'),
  circleXmarkRed: require(path + 'circleXmarkRed.png'),
  squareBlackCheck: require(path + 'squareBlackCheck.png'),
  squareGreenCheck: require(path + 'squareGreenCheck.png'),
  squareRedCheck: require(path + 'squareRedCheck.png'),
  squareBlack: require(path + 'squareBlack.png'),
  angleDown: require(path + 'angleDown.png'),
  pathLearningScreen: require(path + 'pathLearningScreen.png'),
  ActionSheetIcon: require(path + 'ActionSheetIcon.png'),
  arrowRotateRightBlue: require(path + 'arrowRotateRightBlue.png'),
  hourglassEnd: require(path + 'hourglassEnd.png'),
  listUI: require(path + 'listUI.png'),
  cardsblank: require(path + 'cardsblank.png'),
  clipboardQuestion: require(path + 'clipboardQuestion.png'),
  filePdf:  require(path + 'filePdf.png'),
  checkWhite:  require(path + 'checkWhite.png'),
  xmarkWhite:  require(path + 'xmarkWhite.png'),
  squareCheckBlue: require(path + 'squareCheckBlue.png'),
  circleCheckRegular: require(path + 'circleCheckRegular.png'),
  ClozeDropDown: require(path + 'ClozeDropDown.png'),
};

export default IMAGES;
