import { AttestationExam } from "../container/app";

export const ENDPOINT = {
  //auth flow
  basicSettings: '',
  register: 'api/v1/user/register',
  verifyOtp: 'api/v1/user/verifyotp',
  resendOtp: 'api/v1/user/resendotp',
  
  login: 'api/Auth/Login',
  forgotPassword: 'api/Auth/ForgotPassword',
  upcomingEvent: 'api/Event/UpcomingEventList',
  upcomingEventDetails: "api/Event",
  continueLearning: "api/users/GetUserWatchHistory",
  getUserEntities: "api/users/GetUserEntities",
  GetAllTrackCourseStatisticsByUser: "api/dashboard/v2/GetAllTrackCourseStatisticsByUser",
  GetUserTrackCourseMappingsByStatusPassFail: "api/dashboard/v2/GetUserTrackCourseMappingsByStatusPassFail",
  getprofile: "api/Account/getprofile",
  DeleteUserWatchHistory: "api/users/DeleteUserWatchHistory",
  UpdateUserProfile: "api/Account/UpdateUserProfile",
  ChangePassword: "api/auth/ChangePassword",
  courseDetails : "api/courses/v2",
  scromDetails : "api/scorm/Chapter",
  flashCardList : "api/LearningCard",
  AddUserAttemp : "api/LearningCard/AddUserAttempt",
  AddUserAnswer : "api/LearningCard/AddUserAnswer",
  UpdateProgress : "api/LearningCard/UpdateProgress",
  AddCardToRevisitLater : "api/LearningCard/AddCardToRevisitLater",
  GetRevisitCards : "api/LearningCard/GetRevisitCards",
  GetIncorrectUserAnswers : "api/LearningCard/GetIncorrectUserAnswers",
  GetPracticeReport : "api/LearningCard/GetPracticeReport",
  RefreshToken : "api/Auth/RefreshToken",
  GetScormChaptersByCourse : "api/scorm/GetScormChaptersByCourse",
  materialprogress: "api/users/v2/materialprogress",
  ExamAddUserAttempt: "api/Exams/AddUserAttempt",
  Exams : "api/Exams",
  AddKCResponse : "api/Exams/AddKCResponse",
  UpdateKCProgress : "api/Exams/UpdateKCProgress",
  AddExamResponse: "api/Exams/AddResponse",
  GetExamResult : "api/Exams/GetExamResult",
  GetAssignedPathDetailsV2 : "api/BlendedLearnings/GetEnrolledPathDetailsV2",
  AddUpdateLearnersToSlot : "api/BlendedLearnings/AddUpdateLearnersToSlot",
  GoogleSignIn: "api/Auth/GoogleSignIn",
  AppleLogin:"api/Auth/AppleSignIn",
  FacebookSignIn: "api/Auth/FacebookSignIn",
  MicrosoftSignIn: "api/Auth/MicrosoftSignIn",
  IsCompanyExists: "api/Account/IsCompanyExists",
  LoggedTimeEntry:"api/master/LoggedTimeEntry",
  GetUserGamificationPopUpAndTotalPoints:"api/Gamification/GetUserGamificationPopUpAndTotalPoints",
  GetAllBadges:"api/master/GetAllBadges",
  GetMyAchievements:"api/Gamification/GetMyAchievements",
  GetSettings: "api/Settings/GetSettings",
  GetUserGamificationLeaderboard: "api/Gamification/GetUserGamificationLeaderboard",
  GetUserGamificationPointsByEntityAndAssignedDate: "api/Gamification/GetUserGamificationPointsByEntityAndEnrolledDate",

  //GetUserGamificationPopUpAndTotalPoints: "api/Gamification/GetUserGamificationPopUpAndTotalPoints",
  GetAllLevels: "api/master/GetAllLevels",
  createEnrollmentRequest: "api/enrollments/createEnrollmentRequest",
  AttestationQuestions: "api/Attestation/GetQuestions",
  SubmitAttestation: "api/Attestation/SubmitAttestation",
  scormInitialize: "api/scorm/Initialize",
  scormCommit: "api/scorm/Commit",
  resetPassword: 'api/v1/user/resetpassword',
  socialLogin: '',
  nearestParkings: 'api/v1/parkingStructure/findNearBy',
  homescreenServices: '',

  //app flow assignments
    GetAssignment:"api/Assignments/GetAssignment",
    AssignmentSubmission:"api/Assignments/AssignmentSubmission",
    GetTimeOnAssignmentDetail:"api/Assignments/GetTimeOnAssignmentDetail"

};
